//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_pointcloudview : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean EditToolToggleMode
        {
            get
            {
                return SteamVR_Actions.pointcloudview_EditToolToggleMode;
            }
        }
        
        public virtual SteamVR_Action_Boolean MeasureToolToggleState
        {
            get
            {
                return SteamVR_Actions.pointcloudview_MeasureToolToggleState;
            }
        }
        
        public virtual SteamVR_Action_Single Throttle
        {
            get
            {
                return SteamVR_Actions.pointcloudview_Throttle;
            }
        }
        
        public virtual SteamVR_Action_Boolean MoveBackwards
        {
            get
            {
                return SteamVR_Actions.pointcloudview_MoveBackwards;
            }
        }
        
        public virtual SteamVR_Action_Boolean EditToolMoveForward
        {
            get
            {
                return SteamVR_Actions.pointcloudview_EditToolMoveForward;
            }
        }
        
        public virtual SteamVR_Action_Boolean EditToolMoveBackward
        {
            get
            {
                return SteamVR_Actions.pointcloudview_EditToolMoveBackward;
            }
        }
        
        public virtual SteamVR_Action_Boolean EditToolScaleUp
        {
            get
            {
                return SteamVR_Actions.pointcloudview_EditToolScaleUp;
            }
        }
        
        public virtual SteamVR_Action_Boolean EditToolScaleDown
        {
            get
            {
                return SteamVR_Actions.pointcloudview_EditToolScaleDown;
            }
        }
        
        public virtual SteamVR_Action_Boolean EditToolOnOff
        {
            get
            {
                return SteamVR_Actions.pointcloudview_EditToolOnOff;
            }
        }
    }
}
